dbpedia_sparql_url: https://dbpedia.org/sparql
languages:
  en:
    w2v_model: models/embeddings/enwiki_20180420_100d.pkl
    fasttext_model: models/embeddings/cc.en.300.bin

  cz:
    #w2v_model:
    fasttext_model: models/embeddings/cc.cs.300.bin
    name_diminutives: resources/czech_name_diminutives.json

  de:
    w2v_model: models/embeddings/dewiki_20180420_100d.pkl
    fasttext_model: models/embeddings/cc.de.300.bin
